# -*- coding: utf-8 -*-
"""processing_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jfRG2-6dSt1cwErcencGhBqZnzBDGnf5
"""

!pip install -q kaggle

from google.colab import drive
drive.mount('/content/drive')

"""
import kagglehub
import shutil
import os

# --- CẤU HÌNH ---
# Tên thư mục bạn muốn lưu trữ kết quả cuối cùng
MY_DATA_FOLDER = "/content/drive/MyDrive/RAG-practice/my_fashion_data"

# 1. Tải dataset về bộ nhớ đệm (Cache)
print("⏳ Đang tải dataset từ Kaggle (có thể mất vài phút)...")
path_cache = kagglehub.dataset_download("agrigorev/clothing-dataset-full")
print(f"✅ Đã tải xong về cache tại: {path_cache}")

# 2. Tạo thư mục của riêng bạn
if not os.path.exists(MY_DATA_FOLDER):
    os.makedirs(MY_DATA_FOLDER)
    print(f"📁 Đã tạo thư mục mới: {MY_DATA_FOLDER}")

# 3. LỌC VÀ LẤY 2 CÁI CẦN THIẾT
print("\n🔄 Đang sao chép dữ liệu cần thiết...")

# --- Lấy cái 1: File CSV ---
src_csv = os.path.join(path_cache, "images.csv")
dst_csv = os.path.join(MY_DATA_FOLDER, "images.csv")

if os.path.exists(src_csv):
    shutil.copy(src_csv, dst_csv)
    print(f"👉 Đã lấy: images.csv")
else:
    print("❌ Lỗi: Không tìm thấy file csv trong dataset tải về.")

# --- Lấy cái 2: Folder ảnh nén (images_compressed) ---
src_imgs = os.path.join(path_cache, "images_compressed")
dst_imgs = os.path.join(MY_DATA_FOLDER, "images_compressed")

if os.path.exists(src_imgs):
    # Nếu thư mục đích đã có thì xóa đi copy lại cho sạch
    if os.path.exists(dst_imgs):
        shutil.rmtree(dst_imgs)

    shutil.copytree(src_imgs, dst_imgs)
    print(f"👉 Đã lấy: images_compressed (Toàn bộ ảnh nhẹ)")
else:
    print("❌ Lỗi: Không tìm thấy folder images_compressed.")

# 4. Kiểm tra kết quả
print("-" * 30)
print(f"🎉 HOÀN TẤT! Dữ liệu sạch của bạn nằm tại: {MY_DATA_FOLDER}")
print("Danh sách file trong thư mục của bạn:")
print(os.listdir(MY_DATA_FOLDER))

import pandas as pd
import os
import matplotlib.pyplot as plt
from PIL import Image

# ĐƯỜNG DẪN QUAN TRỌNG TRÊN COLAB
BASE_DIR = "/content/drive/MyDrive/RAG-practice/my_fashion_data"
CSV_PATH = os.path.join(BASE_DIR, "images.csv")
# Lưu ý: Chúng ta dùng images_compressed cho nhẹ, đừng dùng images_original
IMAGES_DIR = os.path.join(BASE_DIR, "images_compressed")

# 1. Đọc file CSV
df = pd.read_csv(CSV_PATH)
print(f"Tổng số dòng trong CSV: {len(df)}")

# 2. Lọc bỏ các nhãn nhiễu
df_clean = df[~df['label'].isin(['Not sure', 'Skip', 'Other'])]
print(f"Số lượng ảnh sạch (có nhãn rõ ràng): {len(df_clean)}")

# 3. Hàm lấy đường dẫn ảnh
# ==============================
def get_image_path(image_id):
    return os.path.join(IMAGES_DIR, f"{image_id}.jpg")

# ==============================
# 4. Test hiển thị ảnh + caption + color
# ==============================
try:
    row = df_clean.sample(1).iloc[0]
    img_path = get_image_path(row['image'])

    img = Image.open(img_path).convert("RGB")

    plt.figure(figsize=(5,5))
    plt.imshow(img)
    plt.axis('off')

    title_text = (
        f"Label: {row['label']}\n"
        f"Color: {row.get('color', 'N/A')}"
    )
    plt.title(title_text, fontsize=10)
    plt.show()

    print("🖼 IMAGE ID:", row['image'])
    print("🎨 Color:", row.get('color', 'N/A'))
    print("🏷 Label:", row['label'])
    print("📝 Caption:")
    print(row.get('caption', 'N/A'))

    print("\n✅ Load ảnh + metadata thành công. Dữ liệu sẵn sàng cho Embedding / RAG.")

except Exception as e:
    print(f"❌ Có lỗi xảy ra: {e}")
    print("👉 Kiểm tra lại images_compressed hoặc tên cột trong CSV.")

# Kiểm tra ảnh bị thiếu
missing_images = []

for image_id in df_clean['image']:
    path = get_image_path(image_id)
    if not os.path.exists(path):
        missing_images.append(image_id)

print(f"Số ảnh bị thiếu file: {len(missing_images)}")

print("Các cột trong CSV:")
print(df.columns.tolist())

df_clean['label'].value_counts().plot(kind='bar', figsize=(10,4))
plt.title("Label Distribution")
plt.show()

df.info()

df.head()

df.isnull().sum()

df[df['color'].isnull()]

print("Số lượng label khác nhau:", df['label'].nunique())
df['label'].value_counts().head(17)

dup_count = df_clean['image'].duplicated().sum()
print(f"Số image_id bị trùng: {dup_count}")

from collections import Counter

sizes = []

for image_id in df_clean['image'].sample(100):  # sample cho nhanh
    img = Image.open(get_image_path(image_id))
    sizes.append(img.size)  # (width, height)

Counter(sizes).most_common(10)

!pip install -q -U google-generativeai tqdm

# 1. Loại bỏ các cột thừa
cols_to_remove = ['caption']
df_clean = df_clean.drop(columns=cols_to_remove, errors='ignore')

# 3. Lưu đè lại vào file CSV để cập nhật thay đổi
df_clean.to_csv(CSV_PATH, index=False)
print(f"✅ Đã dọn dẹp và lưu file tại: {CSV_PATH}")

import google.generativeai as genai
import time
from tqdm import tqdm

# Cấu hình API
genai.configure(api_key="**REDACTED_GEMINI_API_KEY**") # Thay bằng key của bạn
model = genai.GenerativeModel('gemini-2.5-flash')

# Test prompt
response = model.generate_content(
    "Viết 1 câu mô tả áo thun màu đỏ đô, phong cách casual."
)

print(response.text)

import os
import time
from tqdm import tqdm
from PIL import Image


# =====================================================
# 🧠 GENERATE FASHION SEARCH CAPTION
# =====================================================
def generate_search_caption(image_path: str) -> str | None:
    """
    Generate a fashion-centric morphological caption for a given image.
    Output: 30–40 words, professional fashion vocabulary.
    """

    prompt = """
    Write a 30-40 word fashion-centric morphological description.
    Focus:
    1. Fabric / Texture
    2. Silhouette / Fit
    3. Construction details (collars, seams, closures)
    4. Overall aesthetic

    Rules:
    - Use professional fashion vocabulary
    - NO colors
    - NO brand names
    - NO generic category names
    - Single paragraph only
    """

    try:
        img = Image.open(image_path)

        response = model.generate_content([prompt, img])

        caption = (
            response.text
            .strip()
            .replace("\n", " ")
            .replace("*", "")
        )

        return caption

    except Exception as e:
        print(f"❌ Lỗi xử lý ảnh {image_path}: {e}")
        return None


# =====================================================
# 📦 PREPARE DATAFRAME
# =====================================================
# Tạo cột caption nếu chưa tồn tại
if "caption" not in df_clean.columns:
    df_clean = df_clean.copy()  # tránh SettingWithCopyWarning
    df_clean["caption"] = None

# Chỉ xử lý các dòng còn thiếu caption
missing_captions = df_clean[df_clean["caption"].isna()]

print(f"🖼️ Cần xử lý: {len(missing_captions)} ảnh")


# =====================================================
# 🔁 MAIN PROCESS LOOP
# =====================================================
for idx, row in tqdm(
    missing_captions.iterrows(),
    total=len(missing_captions),
    desc="Generating captions"
):
    img_path = get_image_path(row["image"])

    if not os.path.exists(img_path):
        print(f"⚠️ Không tìm thấy ảnh: {img_path}")
        continue

    caption = generate_search_caption(img_path)
    if caption:
        df_clean.at[idx, "caption"] = caption

    # 💾 Lưu định kỳ mỗi 20 ảnh
    if idx % 20 == 0:
        df_clean.to_csv(CSV_PATH, index=False)

    # ⏳ Rate limit (Gemini Free ~15 RPM)
    time.sleep(1)


# =====================================================
# ✅ SAVE FINAL RESULT
# =====================================================
df_clean.to_csv(CSV_PATH, index=False)
print(f"✅ Hoàn tất! Caption đã được lưu vào: {CSV_PATH}")

def detect_item_color(image_path, label):
    """Nhận diện màu sắc chủ đạo của sản phẩm"""
    try:
        img = Image.open(image_path)

        # Prompt tập trung vào xác định màu sắc chính xác
        prompt = f"""
        Identify the primary color of this {label}.
        Rules:
        1. Return only the color name(s).
        2. Be specific (e.g., 'Olive Green' instead of just 'Green', 'Charcoal Grey' instead of 'Grey').
        3. If it has a pattern, mention the base color and the pattern type (e.g., 'White with Black stripes').
        4. Max 3-4 words. No full sentences.
        """

        response = model.generate_content([prompt, img])
        return response.text.strip().replace('*', '')
    except Exception as e:
        print(f"Lỗi nhận diện màu tại {image_path}: {e}")
        return None

# --- CHUẨN BỊ CỘT COLOR ---
if 'color' not in df_clean.columns:
    df_clean['color'] = None

# Lọc các dòng chưa có màu sắc
missing_colors = df_clean[df_clean['color'].isna()]
print(f"Cần xử lý màu sắc cho: {len(missing_colors)} ảnh.")

# --- VÒNG LẶP XỬ LÝ ---
for index, row in tqdm(missing_colors.iterrows(), total=len(missing_colors)):
    img_path = get_image_path(row['image'])
    current_label = row['label']

    if os.path.exists(img_path):
        color_result = detect_item_color(img_path, current_label)

        if color_result:
            df_clean.loc[index, 'color'] = color_result

        # Lưu định kỳ
        if index % 20 == 0:
            df_clean.to_csv(CSV_PATH, index=False)

        # Rate limit an toàn (4s cho bản Free)
        time.sleep(1)

# 1. Loại bỏ các cột thừa
cols_to_remove = ['sender_id', 'kids']
df_clean = df_clean.drop(columns=cols_to_remove, errors='ignore')

# 2. Kiểm tra lại cấu trúc bảng
print("Cấu trúc bảng sau khi loại bỏ cột thừa:")
print(df_clean.info())
display(df_clean.head())

# 3. Lưu đè lại vào file CSV để cập nhật thay đổi
df_clean.to_csv(CSV_PATH, index=False)
print(f"✅ Đã dọn dẹp và lưu file tại: {CSV_PATH}")

